db:
  url: "root:1234@tcp(127.0.0.1:3306)/jobgolangzzzzzz"
mail:
  smtp_host : "smtp.gmail.com"
  smtp_port : "587"
  sender: "dlrbcnvk@gmail.com"
  password: "euunvoifgqzwewov"
  receiver: "sgcho7091@gmail.com"
