name: Build and Push Docker Image to Amazon ECR

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행을 위한 이벤트

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Clean up old images in ECR
        run: |
          aws ecr list-images --repository-name ${{ secrets.ECR_REPOSITORY }} --query 'imageIds[*]' | \
          jq '.[].imageDigest' | \
          xargs -I {} aws ecr batch-delete-image --repository-name ${{ secrets.ECR_REPOSITORY }} --image-ids imageDigest={}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Extract Git commit SHA
        id: vars
        run: echo ::set-output name=sha_short::$(git rev-parse --short HEAD)

      - name: Build and push Docker image
        id: build-image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ secrets.ECR_REPOSITORY }}
          tags: ${{ steps.vars.outputs.sha_short }}
          registry: ${{ steps.login-ecr.outputs.registry }}
          platform: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.build-image.outputs.digest }}